### PR TITLE
feat: add player sprites and UI hands

### PR DESCRIPTION
**Pull request by SomeZhmyh**
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAAAAAAAAAAAAAAAAAAA

### CODE REVIEW

**Comment by SomeZhmyh** [comment]
ah yes? it cost me 300 bucks

**Comment by NativeRV** [comment]
ъъъЪЪЪъъъЪЪЪ РАБОТА КИПИТ

**Comment by nativerv** [comment]
> ah yes? it cost me 300 bucks

Without further interruption, let's celebrate and~~

**Comment by Jesus2281337** [comment]
😈🤡🤡🤡

**Pull request merged**
